"""GitHub webhook handler for ClawForge.

Handles GitHub events:
- issues.opened: Auto-analyze issues and suggest fixes
- pull_request.opened: Review PR if related to ClawForge project
- push: Track code changes
"""

import hashlib
import hmac
import re
from dataclasses import dataclass, field
from typing import Any

from clawforge.config import get_settings
from clawforge.llm.client import get_llm_client
from clawforge.storage import get_project_store


@dataclass
class IssueAnalysis:
    """Result of analyzing a GitHub issue."""

    issue_url: str
    issue_title: str
    issue_body: str

    # Analysis results
    is_bug: bool = False
    is_feature_request: bool = False
    is_question: bool = False

    # For bugs
    affected_files: list[str] = field(default_factory=list)
    suggested_fix: str = ""
    confidence: float = 0.0  # 0-1 confidence in the suggested fix

    # For features
    implementation_suggestion: str = ""

    # Cost
    cost_cents: int = 0

    # Action taken
    comment_posted: bool = False
    pr_created: bool = False


def verify_github_signature(payload: bytes, signature: str, secret: str) -> bool:
    """Verify GitHub webhook signature.

    GitHub sends a HMAC-SHA256 signature in the X-Hub-Signature-256 header.
    """
    if not signature or not signature.startswith("sha256="):
        return False

    expected = "sha256=" + hmac.new(
        secret.encode(),
        payload,
        hashlib.sha256,
    ).hexdigest()

    return hmac.compare_digest(expected, signature)


class GitHubWebhookHandler:
    """Handles GitHub webhook events."""

    ISSUE_ANALYSIS_PROMPT = """Analyze this GitHub issue for a Flutter app generated by ClawForge.

## Issue Title
{title}

## Issue Body
{body}

## Project Files
The app has these Dart files:
{file_list}

## Your Task
1. Determine if this is a bug report, feature request, or question
2. If it's a bug:
   - Identify which files are likely affected
   - Suggest a specific fix (code changes)
   - Rate your confidence (0-1) in the fix
3. If it's a feature request:
   - Suggest how to implement it
4. If it's a question:
   - Provide a helpful answer

Respond in this JSON format:
{{
    "type": "bug" | "feature" | "question",
    "affected_files": ["file1.dart", "file2.dart"],
    "analysis": "Your analysis of the issue...",
    "suggested_fix": "// Code changes if applicable...",
    "confidence": 0.8,
    "response_comment": "A helpful comment to post on the issue..."
}}"""

    def __init__(self):
        self.store = get_project_store()

    async def handle_event(self, event_type: str, payload: dict[str, Any]) -> dict[str, Any]:
        """Route GitHub event to appropriate handler."""
        handlers = {
            "issues": self._handle_issue_event,
            "pull_request": self._handle_pr_event,
            "push": self._handle_push_event,
            "ping": self._handle_ping,
        }

        handler = handlers.get(event_type)
        if not handler:
            return {
                "status": "ignored",
                "message": f"Event type '{event_type}' not handled",
            }

        return await handler(payload)

    async def _handle_ping(self, payload: dict[str, Any]) -> dict[str, Any]:
        """Handle GitHub ping event (webhook setup verification)."""
        return {
            "status": "success",
            "message": "Webhook configured successfully",
            "zen": payload.get("zen", ""),
        }

    async def _handle_issue_event(self, payload: dict[str, Any]) -> dict[str, Any]:
        """Handle issue events (opened, edited, closed)."""
        action = payload.get("action")
        issue = payload.get("issue", {})
        repo = payload.get("repository", {})

        if action != "opened":
            return {
                "status": "ignored",
                "message": f"Issue action '{action}' not handled",
            }

        # Find the ClawForge project for this repo
        repo_full_name = repo.get("full_name", "")
        project = await self.store.find_by_repo(repo_full_name)

        if not project:
            return {
                "status": "ignored",
                "message": f"No ClawForge project found for repo '{repo_full_name}'",
            }

        # Analyze the issue
        analysis = await self._analyze_issue(
            title=issue.get("title", ""),
            body=issue.get("body", ""),
            issue_url=issue.get("html_url", ""),
            project_files=project.files,
        )

        # Post a comment if analysis was successful
        if analysis.suggested_fix or analysis.implementation_suggestion:
            comment = await self._create_analysis_comment(analysis)
            # TODO: Post comment via GitHub API
            # For now, just return the analysis

        return {
            "status": "analyzed",
            "issue_url": analysis.issue_url,
            "issue_type": "bug" if analysis.is_bug else "feature" if analysis.is_feature_request else "question",
            "affected_files": analysis.affected_files,
            "has_suggestion": bool(analysis.suggested_fix or analysis.implementation_suggestion),
            "confidence": analysis.confidence,
            "cost_cents": analysis.cost_cents,
        }

    async def _handle_pr_event(self, payload: dict[str, Any]) -> dict[str, Any]:
        """Handle pull request events."""
        action = payload.get("action")
        pr = payload.get("pull_request", {})

        if action not in ["opened", "synchronize"]:
            return {
                "status": "ignored",
                "message": f"PR action '{action}' not handled",
            }

        return {
            "status": "acknowledged",
            "message": f"PR #{pr.get('number')} acknowledged",
            "pr_url": pr.get("html_url"),
        }

    async def _handle_push_event(self, payload: dict[str, Any]) -> dict[str, Any]:
        """Handle push events to track changes."""
        repo = payload.get("repository", {})
        commits = payload.get("commits", [])
        ref = payload.get("ref", "")

        # Only track main/master branch
        if ref not in ["refs/heads/main", "refs/heads/master"]:
            return {
                "status": "ignored",
                "message": f"Push to {ref} ignored (not main branch)",
            }

        return {
            "status": "tracked",
            "repo": repo.get("full_name"),
            "commits_count": len(commits),
            "ref": ref,
        }

    async def _analyze_issue(
        self,
        title: str,
        body: str,
        issue_url: str,
        project_files: list[dict[str, str]],
    ) -> IssueAnalysis:
        """Analyze a GitHub issue using LLM."""
        # Build file list for context
        dart_files = [f["path"] for f in project_files if f.get("path", "").endswith(".dart")]
        file_list = "\n".join(f"- {f}" for f in dart_files[:50])  # Limit to 50 files

        prompt = self.ISSUE_ANALYSIS_PROMPT.format(
            title=title,
            body=body or "(no description provided)",
            file_list=file_list,
        )

        client = get_llm_client(prefer_local=True)

        try:
            response = await client.complete(
                prompt=prompt,
                system="You are a Flutter expert analyzing GitHub issues. Always respond with valid JSON.",
                max_tokens=2000,
            )

            # Parse JSON response
            import json
            result = json.loads(response.text)

            analysis = IssueAnalysis(
                issue_url=issue_url,
                issue_title=title,
                issue_body=body or "",
                cost_cents=response.cost_cents,
            )

            issue_type = result.get("type", "question")
            analysis.is_bug = issue_type == "bug"
            analysis.is_feature_request = issue_type == "feature"
            analysis.is_question = issue_type == "question"

            analysis.affected_files = result.get("affected_files", [])
            analysis.suggested_fix = result.get("suggested_fix", "")
            analysis.confidence = result.get("confidence", 0.0)
            analysis.implementation_suggestion = result.get("analysis", "")

            return analysis

        except Exception as e:
            return IssueAnalysis(
                issue_url=issue_url,
                issue_title=title,
                issue_body=body or "",
                is_question=True,  # Default to question if analysis fails
            )

    async def _create_analysis_comment(self, analysis: IssueAnalysis) -> str:
        """Create a GitHub comment based on the analysis."""
        lines = ["## 🤖 ClawForge Analysis\n"]

        if analysis.is_bug:
            lines.append("This appears to be a **bug report**.\n")

            if analysis.affected_files:
                lines.append("### Potentially Affected Files")
                for f in analysis.affected_files[:5]:
                    lines.append(f"- `{f}`")
                lines.append("")

            if analysis.suggested_fix:
                lines.append("### Suggested Fix")
                lines.append(f"```dart\n{analysis.suggested_fix}\n```")
                lines.append(f"\n*Confidence: {analysis.confidence:.0%}*")

        elif analysis.is_feature_request:
            lines.append("This appears to be a **feature request**.\n")

            if analysis.implementation_suggestion:
                lines.append("### Implementation Suggestion")
                lines.append(analysis.implementation_suggestion)

        else:
            lines.append("This appears to be a **question**.\n")

        lines.append("\n---")
        lines.append("*This analysis was generated automatically by ClawForge.*")

        return "\n".join(lines)


async def handle_github_webhook(
    event_type: str,
    payload: dict[str, Any],
    signature: str | None = None,
) -> dict[str, Any]:
    """Main entry point for handling GitHub webhooks.

    Args:
        event_type: GitHub event type (from X-GitHub-Event header)
        payload: Webhook payload
        signature: Webhook signature (from X-Hub-Signature-256 header)

    Returns:
        Response dict with status and details
    """
    settings = get_settings()

    # Verify signature if webhook secret is configured
    if settings.github_webhook_secret and signature:
        import json
        payload_bytes = json.dumps(payload).encode()
        if not verify_github_signature(payload_bytes, signature, settings.github_webhook_secret):
            return {
                "status": "error",
                "message": "Invalid webhook signature",
            }

    handler = GitHubWebhookHandler()
    return await handler.handle_event(event_type, payload)
